### ISSUE TITLE
Updating to sass-rails 4.0.5 breaks app

### ISSUE THREAD

**Issue by jjwon** [calblueprint/foodshift#107]
Invalid CSS after "...ules: $modules ": expected "}", was "!global;" (in /Users/jason/development/foodshift/app/assets/stylesheets/application.css.scss:13)

**Comment by jjwon** [comment]
Sass::UnitConversionError: Incompatible units: 'rem' and 'px'.

       (in /tmp/build_d0e8ed87afb5823f4171b0b935c4ec52/calblueprint-foodshift-6f87543/app/assets/stylesheets/application.css.scss:247)

**Comment by noahsark769** [comment]
Are you guys using foundation? If so I think we actually had the same issue with revolv. Has to do with the version of libsass not supporting that syntax. Not sure how to fix it though lol, we just downgraded

**Comment by jjwon** [comment]
srsly doe foundation-- y u gotta do me like that.  will fix by updating gemfile lol
