### ISSUE TITLE
When signing up to make Donation, add field for contact person on site

### ISSUE THREAD

**Issue by allileong** [calblueprint/foodshift#62]
### Background
Currently, we ask for the name and contact information for the person who is submitting the Donation information. However, it is very important that whoever is delivering the donation has a way to contact the person who will physically be present to hand off the donation. 

### Task
Add fields to collect the name and phone number for the person who will be on site - might want this to be in a dropdown if the user checks a checkbox saying "I will not be on site to hand off the donation" or something

**Comment by jjwon** [comment]
Looks like its done already!
