### ISSUE TITLE
Edit notification of donation email to the recipient

### ISSUE THREAD

**Issue by allileong** [calblueprint/foodshift#65]
Only display the following information on the email that goes out to recipients when a donation is posted:
* Name of donation organization

**Comment by jjwon** [comment]
@allileong do you know why we wanted to do this?  to me, giving them more information might be better in case the recipient can pick it up for some reason, although i guess they would only need the address in this case instead of phone, email, etc

**Comment by jjwon** [comment]
doesn't really make sense esp without shifter.
