### ISSUE TITLE
Recipient sign-up page: add a hover explaining why only 501c3's can sign up to receive food

### ISSUE THREAD

**Issue by allileong** [calblueprint/foodshift#66]
#### Background
Donors do not have to worry about liabilities associated with food poisoning when donating to nonprofits according to the Bill Emerson Good Samaritan Food Donation Act (http://www.foodtodonate.com/Fdcmain/LegalLiabilities.aspx)
#### Task
Create a hover to briefly explain the above

**Comment by akakitani** [comment]
Resolved with #186
