### ISSUE TITLE
Performance boost

### ISSUE THREAD

**Issue by allileong** [calblueprint/foodshift#71]
Loading the page takes *FOREVER*. How can we make it faster?

**Comment by jjwon** [comment]
I think part of this is because the images on s3 are way too big.  We should rescale them.

Consider this as a resource: https://css-tricks.com/which-responsive-images-solution-should-you-use/

**Comment by jjwon** [comment]
Caching assets on s3???

**Comment by jjwon** [comment]
Closed by #132
