### ISSUE TITLE
Figure out why JS isn't loading

### ISSUE THREAD

**Issue by akakitani** [calblueprint/foodshift#81]
Breaking things like Foundation client-side validation, Google maps API, etc.

Probably an issue with turbolinks - quick fix would be to just take it out?

**Comment by jjwon** [comment]
removing turbolinks solves this, but i'm unsure if this is the "correct" solution.  some information about making onload scripts work with turbolinks here: http://stackoverflow.com/questions/21226357/rails-4-with-turbolinks-and-window-load

**Comment by jjwon** [comment]
meh whatever
