### ISSUE TITLE
Write script to generate test data

### ISSUE THREAD

**Issue by akakitani** [calblueprint/foodshift#84]
Right now we have `db/seeds.rb` that generates some basic data (users and donations), but we need a script to generate records for all the other models we have. Especially need to do this for issue #51. 

Also, is `seeds.rb` the right place to put this kind of script for dummy test data? I was under the impression that this file is for you to run once to generate static data in the db (e.g. a table for all the states in the U.S.)

**Comment by jjwon** [comment]
Closed by #86
